#!/usr/bin/env python3
"""Generate a C++ source file embedding all files from a directory."""
import os
import sys
import mimetypes

def mime_for(path):
    ext = os.path.splitext(path)[1].lower()
    table = {
        '.html': 'text/html',
        '.js':   'application/javascript',
        '.css':  'text/css',
        '.json': 'application/json',
        '.svg':  'image/svg+xml',
        '.png':  'image/png',
        '.ico':  'image/x-icon',
        '.woff': 'font/woff',
        '.woff2':'font/woff2',
        '.ttf':  'font/ttf',
        '.map':  'application/json',
    }
    return table.get(ext, 'application/octet-stream')

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <dist_dir> <output.cpp>", file=sys.stderr)
        sys.exit(1)

    dist_dir  = sys.argv[1]
    out_path  = sys.argv[2]

    entries = []  # (web_path, mime, bytes)

    if os.path.isdir(dist_dir):
        for root, dirs, files in os.walk(dist_dir):
            dirs.sort()
            for fname in sorted(files):
                full = os.path.join(root, fname)
                rel  = os.path.relpath(full, dist_dir)
                web  = '/' + rel.replace(os.sep, '/')
                with open(full, 'rb') as f:
                    data = f.read()
                entries.append((web, mime_for(fname), data))
    else:
        # No dist dir - embed a minimal placeholder index.html
        placeholder = b"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>rtl_433 WebUI</title></head>
<body><h1>rtl_433 WebUI</h1>
<p>Frontend not built. Run <code>npm install &amp;&amp; npm run build</code> in the frontend/ directory.</p>
</body></html>"""
        entries.append(('/index.html', 'text/html', placeholder))

    lines = []
    lines.append('// Auto-generated by embed_generator.py - DO NOT EDIT')
    lines.append('#include <cstddef>')
    lines.append('#include "server.hpp"')
    lines.append('')

    for i, (web_path, mime, data) in enumerate(entries):
        varname = f'g_file_data_{i}'
        lines.append(f'static const unsigned char {varname}[] = {{')
        # wrap at 16 bytes per line
        byte_list = [f'0x{b:02x}' for b in data]
        rows = [', '.join(byte_list[j:j+16]) for j in range(0, len(byte_list), 16)]
        for row in rows:
            lines.append(f'  {row},')
        lines.append('};')
        lines.append('')

    lines.append('const EmbeddedFile g_embedded_files[] = {')
    for i, (web_path, mime, data) in enumerate(entries):
        varname = f'g_file_data_{i}'
        escaped_path = web_path.replace('\\', '\\\\').replace('"', '\\"')
        escaped_mime = mime.replace('"', '\\"')
        lines.append(f'  {{ "{escaped_path}", "{escaped_mime}", {varname}, {len(data)} }},')
    lines.append('};')
    lines.append('')
    lines.append(f'const size_t g_embedded_files_count = {len(entries)};')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Embedded {len(entries)} files into {out_path}")

if __name__ == '__main__':
    main()
